spring:
  datasource:
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    url: jdbc:sqlserver://localhost:1433;DataBaseName=VD;encrypt=false;
    username: sa
    password: ssck@2025
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB